import createClient from 'openapi-fetch';
import type { paths, components } from '../api/xero_accounting'; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: 'https://myapi.dev/v1/' });

type XeroObjects = components['schemas'];
type XeroParameters = components['parameters'];
type XeroResponses = components['responses'];

export type { XeroObjects, XeroParameters, XeroResponses };
export default client;
