import createClient from "openapi-fetch";
import type { paths } from "../api/xero_accounting"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://myapi.dev/v1/" });

export default client;